<?php
// ============================================
// One-off demo-data seeder for showing the forecasting pipeline in action.
// Reads ml/data/_demo_seed_payload.json (generated by a throwaway Python
// script) and inserts it via the app's own PDO connection, so
// password_hash()/PASSWORD_DEFAULT matches login.php exactly.
//
// Safe to re-run: it deletes any existing users with these demo emails
// first (ON DELETE CASCADE takes goals/goal_logs/transactions/
// focus_sessions/forecast_cache with them), then re-inserts fresh.
//
// Usage:  C:\xampp\php\php.exe ml\seed_demo_users.php
// ============================================
require_once __DIR__ . '/../includes/db.php';

$payload = json_decode(file_get_contents(__DIR__ . '/data/_demo_seed_payload.json'), true);
if (!$payload) { fwrite(STDERR, "Could not read _demo_seed_payload.json\n"); exit(1); }

$pdo->beginTransaction();
try {
    // ---- wipe any previous run of these same demo accounts ----
    $emails = array_column($payload['users'], 'email');
    $in = implode(',', array_fill(0, count($emails), '?'));
    $pdo->prepare("DELETE FROM users WHERE email IN ($in)")->execute($emails);

    // ---- categories slug -> id ----
    $cat_map = [];
    foreach ($pdo->query("SELECT id, slug FROM categories") as $row) {
        $cat_map[$row['slug']] = $row['id'];
    }

    // ---- users ----
    $user_ids = []; // persona index -> user id
    $ins_user = $pdo->prepare("INSERT INTO users (full_name, email, password_hash, avatar_color, gender) VALUES (?,?,?,?,?)");
    foreach ($payload['users'] as $i => $u) {
        $hash = password_hash($u['password'], PASSWORD_DEFAULT);
        $ins_user->execute([$u['full_name'], $u['email'], $hash, $u['avatar_color'], $u['gender']]);
        $user_ids[$i] = (int)$pdo->lastInsertId();
    }

    // ---- goals ----
    $goal_ids = []; // "persona|title" -> goal id
    $ins_goal = $pdo->prepare("INSERT INTO goals (user_id, category_id, title, description, frequency, target_per_week, est_minutes) VALUES (?,?,?,?,?,?,?)");
    foreach ($payload['goals'] as $g) {
        $uid = $user_ids[$g['persona']];
        $cid = $cat_map[$g['category_slug']];
        $ins_goal->execute([$uid, $cid, $g['title'], $g['description'], $g['frequency'], $g['target_per_week'], $g['est_minutes']]);
        $goal_ids[$g['persona'] . '|' . $g['title']] = (int)$pdo->lastInsertId();
    }

    // ---- goal_logs ----
    $ins_log = $pdo->prepare("INSERT IGNORE INTO goal_logs (goal_id, log_date, status) VALUES (?,?,?)");
    $n_logs = 0;
    foreach ($payload['goal_logs'] as $l) {
        $gid = $goal_ids[$l['persona'] . '|' . $l['goal_title']];
        $ins_log->execute([$gid, $l['log_date'], $l['status']]);
        $n_logs++;
    }

    // ---- transactions ----
    $ins_txn = $pdo->prepare("INSERT INTO transactions (user_id, type, category, amount, txn_date, note) VALUES (?,?,?,?,?,?)");
    foreach ($payload['transactions'] as $t) {
        $uid = $user_ids[$t['persona']];
        $ins_txn->execute([$uid, $t['type'], $t['category'], $t['amount'], $t['txn_date'], $t['note']]);
    }

    // ---- focus_sessions ----
    $ins_focus = $pdo->prepare("INSERT INTO focus_sessions (user_id, goal_id, planned_minutes, actual_minutes, status, started_at) VALUES (?,?,?,?,?,?)");
    foreach ($payload['focus_sessions'] as $f) {
        $uid = $user_ids[$f['persona']];
        $gid = isset($f['goal_title']) ? ($goal_ids[$f['persona'] . '|' . $f['goal_title']] ?? null) : null;
        $ins_focus->execute([$uid, $gid, $f['planned_minutes'], $f['actual_minutes'], $f['status'], $f['started_at']]);
    }

    // ---- mood_logs (calibrated from the real Sleep Health & Lifestyle dataset) ----
    $n_moods = 0;
    if (!empty($payload['mood_logs'])) {
        $ins_mood = $pdo->prepare("INSERT IGNORE INTO mood_logs (user_id, log_date, mood, sleep_hours, stress_level) VALUES (?,?,?,?,?)");
        foreach ($payload['mood_logs'] as $ml) {
            $uid = $user_ids[$ml['persona']];
            $ins_mood->execute([$uid, $ml['log_date'], $ml['mood'], $ml['sleep_hours'], $ml['stress_level']]);
            $n_moods++;
        }
    }

    $pdo->commit();

    echo "Seeded demo users:\n";
    foreach ($payload['users'] as $i => $u) {
        echo "  - {$u['full_name']} <{$u['email']}> / password: {$u['password']}  (user_id={$user_ids[$i]})\n";
    }
    echo "goals: " . count($payload['goals']) . "\n";
    echo "goal_logs: $n_logs\n";
    echo "transactions: " . count($payload['transactions']) . "\n";
    echo "focus_sessions: " . count($payload['focus_sessions']) . "\n";
    echo "mood_logs: $n_moods\n";
} catch (Exception $e) {
    $pdo->rollBack();
    fwrite(STDERR, "Seeding failed, rolled back: " . $e->getMessage() . "\n");
    exit(1);
}
