-- ============================================================
-- Migration: What-If / Scenario Simulation cache  (ADDITIVE)
-- ------------------------------------------------------------
-- Run this ONCE in phpMyAdmin (or `mysql < migration_whatif.sql`)
-- after database/schema.sql and database/migration_burnout.sql.
--
-- This migration is purely additive: it CREATEs two new tables and
-- does not ALTER, DROP or otherwise touch `forecast_cache`,
-- `burnout_predictions`, or any other existing table. The existing
-- ML forecasting pipeline (ml/train_model.py -> forecast_cache ->
-- analyse.php) keeps working unchanged whether or not you run this.
-- ============================================================

USE habit_tracker;

-- ---------- What-If scenario grids ----------
-- Written by ml/whatif_engine.py, read (never written) by simulate.php.
-- One row per (user, category). Re-running the engine overwrites in place,
-- exactly the same "run once, read many times" contract forecast_cache uses.
--
-- `payload` holds the whole precomputed scenario grid for that category:
-- every lever value the slider can take, each with the prediction the
-- EXISTING model returned for that modified input. Precomputing the grid
-- (instead of shelling out to Python on every slider drag) is what lets the
-- simulator stay instant and keeps the live web app free of any runtime
-- Python dependency — the same reason forecast_cache exists.
CREATE TABLE IF NOT EXISTS whatif_cache (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    category ENUM('finance','habits','productivity') NOT NULL,
    payload JSON NOT NULL,
    lever_key VARCHAR(50) DEFAULT NULL,
    model_used VARCHAR(50) DEFAULT NULL,
    generated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_user_category (user_id, category),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ---------- Hugging Face AI insight cache ----------
-- Written and read by the PHP AI layer (includes/ai_insight.php).
-- Caching matters for three reasons: the free Hugging Face tier is
-- rate-limited, the same scenario asked twice should give the same
-- answer during a demo, and a cached insight is still displayable when
-- the API is unreachable. `scenario_hash` is a hash of the exact
-- structured numbers sent to the model, so changing a slider produces a
-- new cache key while re-opening the same scenario reuses the old one.
--
-- `source` records where the text actually came from, so the UI can be
-- honest about it: 'huggingface' = generated by the remote model,
-- 'fallback' = generated by the local rule-based writer because the API
-- was unavailable.
CREATE TABLE IF NOT EXISTS ai_insight_cache (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    category VARCHAR(20) NOT NULL,
    scenario_hash CHAR(40) NOT NULL,
    model_id VARCHAR(120) DEFAULT NULL,
    source ENUM('huggingface','fallback') NOT NULL DEFAULT 'fallback',
    prompt_payload JSON NOT NULL,
    insight_text TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_user_scenario (user_id, scenario_hash),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
